### ISSUE TITLE
want to update readme.md file 

### ISSUE THREAD

**Issue by rani620** [khawajaazfar2000/Hacktoberfest2022-Repository-3#35]
Sir I want to add more in readme file so that contributor  can get a better understanding about the repo.

**Comment by khawajaazfar2000** [comment]
Go ahead, you dont need to create an issue for it.

**Comment by rani620** [comment]
ok sir

**Comment by rani620** [comment]
can i add screenshot of the web page in the readme.md file

**Comment by khawajaazfar2000** [comment]
sure
