### ISSUE TITLE
outdated README.md

### ISSUE THREAD

**Issue by aakritiguptaa** [khawajaazfar2000/Hacktoberfest2022-Repository-3#46]
Hello Maintainer!

I've noticed that the repository has an out-of-date README.md file.
I'd like to update it to the 2022 Hacktober, unless this was intentional.

Keeping the `README.md` relevant to this year's event would attract more contributors to the repo
It would be amazing if I could be assigned to this issue.

Thank you!
Aakriti

**Comment by khawajaazfar2000** [comment]
Go ahead you don't need to create issue for it.
