### ISSUE TITLE
Improving CONTRIBUTING.md

### ISSUE THREAD

**Issue by aakritiguptaa** [khawajaazfar2000/Hacktoberfest2022-Repository-3#47]
Hello Maintainer!
I've noticed that the `CONTRIBUTING.md` file of the repository, though concise, isn't very clear and easy to understand. Especially for newbies who are just starting out into the Hacktober contributions.

I would like to add CLI commands along with clearly indented, easy to follow instructions.
Hoping that I could be assigned to this issue, as I can then improve the repo as soon as possible.

Thanks! 
Aakriti

**Comment by khawajaazfar2000** [comment]
Go ahead you don't need to create issue for it.
